services:
#    admin.example:
#        class: AdminBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

      admin.base_controller:
          class: AdminBundle\Controller\BaseController
          abstract: true
          calls:
              - [ Initialize, ["@session"] ]

      admin.default_controller:
          class: AdminBundle\Controller\DefaultController
          arguments: ["@app.user_repository","@app.label_repository"]
          parent: "admin.base_controller"

      admin.user_controller:
          class: AdminBundle\Controller\UserController
          arguments: ["@app.user_repository"]
          parent: "admin.base_controller"

      admin.payment_controller:
          class: AdminBundle\Controller\PaymentController
          arguments: ["@app.user_repository","@app.payment_repository"]
          parent: "admin.base_controller"

      admin.advertiser_controller:
          class: AdminBundle\Controller\AdvertiserController
          arguments: ["@app.advertiser_repository"]
          parent: "admin.base_controller"

      admin.url_controller:
          class: AdminBundle\Controller\UrlController
          arguments: ["@app.url_repository"]
          parent: "admin.base_controller"

      admin.setting_controller:
          class: AdminBundle\Controller\SettingController
          arguments: ["@app.settings_repository"]
          parent: "admin.base_controller"

