user:
    resource: "@UserBundle/Controller/"
    prefix:   /user
    type:     annotation

admin:
    resource: "@AdminBundle/Controller/"
    prefix:   /admin
    type:     annotation

app:
    resource: "@AppBundle/Controller/"
    prefix:   /
    type:     annotation
